### PR TITLE
FOX-5206 Method added for fetching orders by client reference.

### PR DESCRIPTION
**Pull request by kish9nine**

### CODE REVIEW

**Comment by denmarkin** [comment]
Let's bump the version to 2.0.1

image

We also need: 
- run full test suite for `rake`
- add docs for new method
image

 - add an example into examples/cli.rb:
image

**Comment by amhed** [comment]
Did you edit the files from windows or os x? the line endings are different, making the diffs harder to read

**Comment by denmarkin** [comment]
@amhed she's on it. For now use `?w=1`

**Comment by denmarkin** [comment]
Code for me looks fine

**Comment by amhed** [comment]
Whoa! MIND BLOWN, had NO IDEA I could pass that parameter

**Comment by denmarkin** [comment]
@dkokotov ca

**Pull request closed without merging**
